### ISSUE TITLE
feat: 添加命令行工具支持，允许通过npx直接运行并支持文件/参数配置

### ISSUE THREAD

**Issue by h7ml** [HCLonely/all-pusher-api#11]
### 功能需求
1. **npx直接运行支持**
   - 将核心功能封装为命令行工具，可通过`npx all-pusher-api`直接调用
   - 支持通过`--config`参数指定配置文件路径（JSON/YAML）
   - 支持通过`--message-file`参数指定消息内容文件路径

2. **多途径配置支持**
   ```bash
   # 示例：混合使用配置文件和命令行参数
   npx all-pusher-api \
     --config ./config.yaml \
     --message-file ./message.md \
     --platforms.dingtalk.key.token $DINGTALK_TOKEN
   ```

3. **消息内容输入方式**
   ```bash
   # 方式1：直接传递消息内容
   npx all-pusher-api -m "紧急通知！服务器宕机！"
   
   # 方式2：从文件读取内容
   npx all-pusher-api --message-file ./alert.md
   
   # 方式3：管道输入
   cat status.txt | npx all-pusher-api
   ```

### 建议配置格式（config.yaml）
```yaml
platforms:
  - name: DingTalk
    config:
      key:
        token: "钉钉机器人token"
        secret: "加签密钥"
    extraOptions:
      isAtAll: true

  - name: WxPusher
    config:
      token: "wxpusher_token"
      uids: ["UID_1", "UID_2"]

messageOptions:
  defaultType: markdown
  titleTemplate: "[系统报警] {title}"
```

### 预期功能示例
```bash
# 完整示例
npx all-pusher-api \
  --config ./config.yaml \
  --message-file ./alert.md \
  --type html \
  --platforms.telegram.chat_id @mychannel
```

### 建议实现方案
1. 添加`cli.js`作为命令行入口
2. 使用commander.js处理命令行参数
3. 支持配置合并逻辑（命令行参数 > 配置文件 > 默认值）
4. 添加文件监听模式（--watch）用于持续监控文件变化

**是否需要提交PR**：  
是的，我可以为这个功能提交PR。如果作者同意此方案，我可以开始实现相关功能。
